global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kafka_producer"
    static_configs:
      - targets: ["localhost:2112"]

  - job_name: "kafka_consumer"
    static_configs:
      - targets: ["localhost:2113"]
